version: '3.7'

services:
  php:
    image: shin1x1/php-dev:7.4-fpm-buster
    depends_on:
      - db
    volumes:
      - .:/var/www/app:cached
      - ./docker/php.ini:/usr/local/etc/php/php.ini

  db:
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    image: postgres:latest
    ports:
      - 5432:5432

  web:
    depends_on:
      - php
    image: nginx
    ports:
      - 8080:80
    volumes:
      - .:/var/www/app:cached
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
