version: '3.7'

services:
  db:
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    image: postgres:13
    ports:
      - 5432:5432
    volumes:
      - ./init.d:/docker-entrypoint-initdb.d

  php:
    image: shin1x1/php-dev:8.0-fpm-buster
    depends_on:
      - db
    volumes:
      - ..:/var/www/app:cached
      - ./php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www/app

  web:
    command: >
      /bin/bash -c
      "envsubst '$$HOSTNAME' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    depends_on:
      - php
    environment:
      - HOSTNAME=${HOSTNAME}
    image: nginx
    ports:
      - 18080:80
    volumes:
      - ..:/var/www/app:cached
      - ./web.template:/etc/nginx/conf.d/default.template
